# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path
import sys

BASE_DIR = Path(SPECPATH).resolve().parent
sys.path.insert(0, str(BASE_DIR))


a = Analysis(
    [str(BASE_DIR / 'desktop' / 'main_desktop.py')],
    pathex=[str(BASE_DIR), str(BASE_DIR / 'web' / 'backend')],

    binaries=[],
    datas=[
        (str(BASE_DIR / 'assets'), 'assets'),
        (str(BASE_DIR / 'data' / 'characters.db'), 'data'),
        (str(BASE_DIR / 'desktop'), 'desktop'),
        (str(BASE_DIR / 'templates'), 'templates'),
        (str(BASE_DIR / 'rules'), 'rules'),
        (str(BASE_DIR / 'creators'), 'creators'),
        (str(BASE_DIR / 'etl'), 'etl'),
        (str(BASE_DIR / 'utils'), 'utils'),
        (str(BASE_DIR / 'db'), 'db'),
        (str(BASE_DIR / 'models'), 'models'),
        (str(BASE_DIR / 'parsers'), 'parsers'),
        (str(BASE_DIR / 'web' / 'frontend' / 'dist'), 'web/frontend/dist'),
        (str(BASE_DIR / 'web' / 'backend' / 'app'), 'web/backend/app'),
        (str(BASE_DIR / 'web' / 'backend' / 'app'), 'app'),
    ],

    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSvg',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'desktop.gui.web_view',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi.staticfiles',
        'starlette.staticfiles',
        'app',
        'app.main',
        'app.core',
        'app.core.config',
        'app.core.database',
        'app.routers',
        'app.routers.auth',
        'app.routers.characters',
        'app.routers.rules',
        'app.routers.sync',
        'app.routers.systems',
        'app.services',
        'app.services.auth_service',
        'app.services.character_service',
        'app.services.rules_service',
        'app.models',
        'app.models.user',
        'app.models.content',
        'app.models.gm',
        'app.models.progression',
        'web.backend.app.main',
        'web.backend.app.routers.auth',
        'web.backend.app.routers.characters',
        'web.backend.app.routers.rules',
        'web.backend.app.routers.sync',
        'web.backend.app.routers.systems',
        'sqlite3',
        'yaml',
        'pypdf',
        'reportlab',
        'requests',
        'urllib3',
        'certifi',
        'json',
        'uuid',
        'db',
        'db.entity_store',
        'models',
        'models.entity',
        'parsers',
        'parsers.base',
        'parsers.pf1e_parser',
        'rules',
        'rules.calculators',
        'rules.character_manager',
        'creators',
        'creators.base_creator',
        'etl',
        'etl.pipeline',
        'utils',
        'utils.data_loader',
        'utils.storage',
        'utils.soft_validation',
        'utils.export_pdf',
    ],


    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.Qt3DCore',
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.Qt3DExtras',
        'PySide6.QtQuick',
        'PySide6.QtQuick3D',
        'PySide6.QtQuickControls2',
        'PySide6.QtQuickWidgets',
        'PySide6.QtQml',
        'PySide6.QtQmlModels',
        'PySide6.QtSensors',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtBluetooth',
        'PySide6.QtPositioning',
        'PySide6.QtNfc',
        'PySide6.QtSpatialAudio',
        'PySide6.QtTest',
        'PySide6.QtPdf',
        'PySide6.QtPdfWidgets',
        'tkinter',
        'matplotlib',
        'scipy',
        'numpy',
        'pandas',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Diyargezen',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=str(BASE_DIR / 'assets' / 'diyargezer_logo.png') if (BASE_DIR / 'assets' / 'diyargezer_logo.png').exists() else None,

    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Diyargezen',
)
